apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qdrantclusters.qdrant.operator
  labels:
    app: qdrant-operator
spec:
  group: qdrant.operator
  names:
    plural: qdrantclusters
    singular: qdrantcluster
    kind: QdrantCluster
    shortNames: []
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Replicas
      description: The desired number of Qdrant replicas in the cluster
      jsonPath: .spec.replicas
      type: integer
    - name: Status
      description: The state of the custom resource
      jsonPath: .status.qdrantStatus
      type: string
    schema:
      openAPIV3Schema:
        description: "A Qdrant cluster definition"
        type: object
        required: ["kind", "apiVersion", "spec"]
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: "Specs of the Qdrant cluster"
            type: object
            x-kubernetes-preserve-unknown-fields: true
            required: ["replicas","image"]
            properties:
              apikey:
                description: "Enable or disable or use pre-defined apikey"
                type: string
                default: "false"
              image:
                type: string
              config:
                description: "Custom Qdrant configuration"
                type: object
                x-kubernetes-preserve-unknown-fields: true
              replicas:
                type: integer
                minimum: 1
              service:
                type: string
                enum: ["ClusterIP", "NodePort", "LoadBalancer"]
                default: ClusterIP
              persistence:
                description: "Parameters for dynamic volume claims"
                type: object
                required: ["size"]
                properties:
                  size:
                    type: string
                    pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                  storageClassName:
                    type: string
                    default: "default"
              resources:
                type: object
                properties:
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
              tls:
                type: object
                required: ["enabled"]
                properties:
                  enabled:
                    type: boolean
                  secretName:
                    type: string
              # scheduling options
              tolerations:
                type: array
                items:
                  type: object
                  properties:
                    key:
                      type: string
                    operator:
                      type: string
                      enum:
                        - Equal
                        - Exists
                    value:
                      type: string
                    effect:
                      type: string
                      enum:
                        - NoExecute
                        - NoSchedule
                        - PreferNoSchedule
                    tolerationSeconds:
                      type: integer
              nodeAffinity:
                type: object
                properties:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    type: array
                    items:
                      type: object
                      required:
                      - preference
                      - weight
                      properties:
                        preference:
                          type: object
                          properties:
                            matchExpressions:
                              type: array
                              items:
                                type: object
                                required:
                                - key
                                - operator
                                properties:
                                  key:
                                    type: string
                                  operator:
                                    type: string
                                  values:
                                    type: array
                                    items:
                                      type: string
                            matchFields:
                              type: array
                              items:
                                type: object
                                required:
                                - key
                                - operator
                                properties:
                                  key:
                                    type: string
                                  operator:
                                    type: string
                                  values:
                                    type: array
                                    items:
                                      type: string
                        weight:
                          format: int32
                          type: integer
                  requiredDuringSchedulingIgnoredDuringExecution:
                    type: object
                    required:
                    - nodeSelectorTerms
                    properties:
                      nodeSelectorTerms:
                        type: array
                        items:
                          type: object
                          properties:
                            matchExpressions:
                              type: array
                              items:
                                type: object
                                required:
                                - key
                                - operator
                                properties:
                                  key:
                                    type: string
                                  operator:
                                    type: string
                                  values:
                                    type: array
                                    items:
                                      type: string
                            matchFields:
                              type: array
                              items:
                                type: object
                                required:
                                - key
                                - operator
                                properties:
                                  key:
                                    type: string
                                  operator:
                                    type: string
                                  values:
                                    type: array
                                    items:
                                      type: string
              podAntiAffinity:
                type: object
                properties:
                  preferredDuringSchedulingIgnoredDuringExecution:
                    type: array
                    items:
                      type: object
                      properties:
                        podAffinityTerm:
                          type: object
                          properties:
                            labelSelector:
                              type: object
                              properties:
                                matchExpressions:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                      values:
                                        type: array
                                        items:
                                          type: string
                                matchLabels:
                                  x-kubernetes-preserve-unknown-fields: true
                                  type: object
                            namespaceSelector:
                              type: object
                              properties:
                                matchExpressions:
                                  type: array
                                  items:
                                    type: object
                                    properties:
                                      key:
                                        type: string
                                      operator:
                                        type: string
                                      values:
                                        type: array
                                        items:
                                          type: string
                                matchLabels:
                                  x-kubernetes-preserve-unknown-fields: true
                                  type: object
                            namespaces:
                              type: array
                              items:
                                type: string
                            topologyKey:
                              type: string
                        weight:
                          type: integer
                  requiredDuringSchedulingIgnoredDuringExecution:
                    type: array
                    items:
                      type: object
                      properties:
                        labelSelector:
                          type: object
                          properties:
                            matchExpressions:
                              type: array
                              items:
                                type: object
                                properties:
                                  key:
                                    type: string
                                  operator:
                                    type: string
                                  values:
                                    type: array
                                    items:
                                      type: string
                            matchLabels:
                              x-kubernetes-preserve-unknown-fields: true
                              type: object
                        namespaceSelector:
                          type: object
                          properties:
                            matchExpressions:
                              type: array
                              items:
                                type: object
                                properties:
                                  key:
                                    type: string
                                  operator:
                                    type: string
                                  values:
                                    type: array
                                    items:
                                      type: string
                            matchLabels:
                              x-kubernetes-preserve-unknown-fields: true
                              type: object
                        namespaces:
                          type: array
                          items:
                            type: string
                        topologyKey:
                          type: string
              topologySpreadConstraints:
                type: array
                items:
                  type: object
                  properties:
                    labelSelector:
                      type: object
                      properties:
                        matchExpressions:
                          type: array
                          items:
                            type: object
                            properties:
                              key:
                                type: string
                              operator:
                                type: string
                              values:
                                type: array
                                items:
                                  type: string
                        matchLabels:
                          x-kubernetes-preserve-unknown-fields: true
                          type: object
                    matchLabelKeys:
                      type: array
                      items:
                        type: string
                    maxSkew:
                      type: integer
                    minDomains:
                      type: integer
                    nodeAffinityPolicy:
                      type: string
                    nodeTaintsPolicy:
                      type: string
                    topologyKey:
                      type: string
                    whenUnsatisfiable:
                      type: string
          status:
            type: object
            properties:
              qdrantStatus:
                type: string
