apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qdrantclusters.qdrant.operator
  labels:
    app: qdrant-operator
spec:
  group: qdrant.operator
  names:
    plural: qdrantclusters
    singular: qdrantcluster
    kind: QdrantCluster
    shortNames: []
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - name: Replicas
      description: The desired number of Qdrant replicas in the cluster
      jsonPath: .spec.replicas
      type: integer
    - name: Status
      description: The state of the custom resource
      jsonPath: .status.qdrantStatus
      type: string
    schema:
      openAPIV3Schema:
        description: "A Qdrant cluster definition"
        type: object
        required: ["kind", "apiVersion", "spec"]
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: "Specs of the Qdrant cluster"
            type: object
            x-kubernetes-preserve-unknown-fields: true
            required: ["replicas"]
            properties:
              apikey:
                description: "Enable or disable or use pre-defined apikey"
                type: string
                default: "false"
              config:
                description: "Custom Qdrant configuration"
                type: object
                x-kubernetes-preserve-unknown-fields: true
              replicas:
                type: integer
                minimum: 1
              service:
                type: string
                enum: ["ClusterIP", "NodePort", "LoadBalancer"]
                default: ClusterIP
              resources:
                type: object
                properties:
                  limits:
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
                  requests:
                    type: object
                    properties:
                      cpu:
                        type: string
                        pattern: '^(\d+m|\d+(\.\d{1,3})?)$'
                      memory:
                        type: string
                        pattern: '^(\d+(e\d+)?|\d+(\.\d+)?(e\d+)?[EPTGMK]i?)$'
          status:
            type: object
            properties:
              qdrantStatus:
                type: string
