apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qdrantcollections.qdrant.operator
  labels:
    app: qdrant-operator
spec:
  group: qdrant.operator
  names:
    plural: qdrantcollections
    singular: qdrantcollections
    kind: QdrantCollection
    shortNames: []
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        description: "A Qdrant collection definition"
        type: object
        required: ["kind", "apiVersion", "spec"]
        properties:
          apiVersion:
            type: string
          kind:
            type: string
          metadata:
            type: object
          spec:
            description: "Specs of the Qdrant collection"
            type: object
            required: ["cluster","vectorSize"]
            properties:
              cluster:
                type: string
              vectorSize:
                type: integer
              shardNumber:
                type: integer
                minimum: 1
                default: 1
              replicationFactor:
                type: integer
                minimum: 1
                default: 1
              onDisk:
                type: boolean
                default: true
              config:
                description: "Custom Qdrant collection configuration"
                type: object
                x-kubernetes-preserve-unknown-fields: true
              snapshots:
                type: object
                required: ["s3EndpointURL", "s3CredentialsSecretName", "bucketName"]
                properties:
                  backupNow:
                    type: boolean
                    default: false
                  backupSchedule:
                    type: string
                    default: ""
                  restoreSnapshotName:
                    type: string
                    default: ""
                  s3EndpointURL:
                    type: string
                  s3CredentialsSecretName:
                    type: string
                  bucketName:
                    type: string



