apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: qdrantclusters.qdrant.operator
  labels:
    app: qdrant-operator
spec:
  group: qdrant.operator
  names:
    plural: qdrantclusters
    singular: qdrantcluster
    kind: QdrantCluster
    shortNames: []
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          description: "A Qdrant cluster definition"
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              description: "Specs of the Qdrant cluster"
              type: object
              x-kubernetes-preserve-unknown-fields: true
          required: ["spec"]

