---
apiVersion: v1
kind: Namespace
metadata:
  name: qdrant-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qdrant-operator-sa
  namespace: qdrant-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: qdrant-operator-role
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get","list","watch"]
  - apiGroups: ["qdrant.operator"]
    resources: ["qdrantclusters", "qdrantclusters/status", "qdrantcollections", "qdrantcollections/status"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: [""]
    resources: ["namespaces", "secrets", "configmaps", "services"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["policy"]
    resources: ["poddisruptionbudgets"]
    verbs: ["get", "list", "create", "watch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list", "create", "update", "delete", "patch", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: qdrant-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: qdrant-operator-role
subjects:
  - kind: ServiceAccount
    name: qdrant-operator-sa
    namespace: qdrant-operator
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: qdrant-operator-config
  namespace: qdrant-operator
data:
  CLUSTER_DOMAIN: "cluster.local"
  DEBUG_MODE: "true"
  NODE_TLS_REJECT_UNAUTHORIZED: "0"
  NODE_OPTIONS: "--no-warnings"
  JOB_IMAGE: "dganochenko/qdrant-operator:0.3.2"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qdrant-operator
  namespace: qdrant-operator
  labels: &labels
    app: qdrant-operator
    component: operator
spec:
  replicas: 3
  selector:
    matchLabels: *labels
  template:
    metadata: 
      labels: *labels
    spec:
      serviceAccountName: qdrant-operator-sa
      terminationGracePeriodSeconds: 10
      containers:
      - name: operator
        image: dganochenko/qdrant-operator:0.3.2
        imagePullPolicy: Always
        # debug
        # command: ["/bin/sh"]
        # args: ["-c", "while true; do echo hello; sleep 10;done"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: qdrant-operator-config
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace

