apiVersion: qdrant.operator/v1alpha1
kind: QdrantCluster
metadata:
  name: test
spec:
  replicas: 1
  image: qdrant/qdrant:v1.7.3
  #apikey: 'newkey'
  config:
    cluster:
      enabled: false
  # persistence:
  #  size: 1Gi
  #  storageClassName: default
  #tls:
  #  enabled: true
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 650m
      memory: 600Mi
