apiVersion: qdrant.operator/v1alpha1
kind: QdrantCluster
metadata:
  name: my-cluster
spec:
  replicas: 3
  image: qdrant/qdrant:v1.7.3
  apikey: 'true'
  # apikey: 'yourkey'
  # Optional. If not declared - the operator will generate new random key
  readApikey: 'true'
  # readApikey: 'yourreadonlykey'
  # Optional. Can be declared if spec.apikey enabled only
  config:
    cluster:
      consensus:
        tick_period_ms: 50
  persistence:
    size: 1Gi
    storageClassName: default
  tls:
    enabled: true
    # secretName: secretname
    # Optional. This secret should contain the next fields: cert.pem, key.pem and cacert.pem
    # If not declared - the operator will generate new CA and certificate
  sidecarContainers:
  - name: nginx
    image: nginx:1.25
    ports:
    - containerPort: 80
  additionalVolumes:
  - name: qdrant-newfolder
    emptyDir: {}
  additionalVolumeMounts:
  - name: qdrant-newfolder
    mountPath: /qdrant/newfolder
  resources:
    requests:
      cpu: 10m
      memory: 100Mi
    limits:
      cpu: 1000m
      memory: 500Mi
  # scheduling options
  tolerations:
  - key: "app.stateful/component"
    operator: "Equal"
    value: "qdrant-operator"
    effect: NoSchedule
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 1
      preference:
        matchExpressions:
        - key: "app.stateful/component"
          operator: In
          values:
          - "qdrant-operator"
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: clustername
            operator: In
            values:
            - my-cluster
        topologyKey: kubernetes.io/hostname
  topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: "topology.kubernetes.io/zone"
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        clustername: my-cluster
        component: qdrant
 

