apiVersion: qdrant.operator/v1alpha1
kind: QdrantCluster
metadata:
  name: test
spec:
  replicas: 1
  apikey: 'newkeyuu2'
  config:
    cluster:
      enabled: false
  persistence:
    size: 1Gi
    storageClassName: default
  resources:
    requests:
      cpu: 200m
      memory: 128Mi
    limits:
      cpu: 220m
      memory: 128Mi
