on:
  pull_request:
    #paths:
    #  - '.github/workflows/ci.yml'
    #  - 'deploy/**'
    #  - 'src/**'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ttl.sh
          image: qdrant-operator
          tag: 1h
          path: src/
          build_file: Dockerfile
          password: blankpassword
          debug: true
