on:
  pull_request:
    #paths:
    #  - '.github/workflows/ci.yml'
    #  - 'deploy/**'
    #  - 'src/**'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Kaniko build
        uses: aevea/action-kaniko@master
        with:
          registry: ttl.sh
          image: qdrant-operator
          tag: 1h
          path: src/
          build_file: Dockerfile
          password: nopasswordatall
      - name: Install K3S
        uses: nolar/setup-k3d-k3s@v1
        with:
          version: v1.26
      - name: Install qdrant-operator
        run: |
          kubectl apply -f deploy/crds/
          sed 's|image: .*$|image: ttl.sh/qdrant-operator:1h|' deploy/operator.yaml | kubectl apply -f -
          kubectl rollout status deploy/qdrant-operator -n qdrant-operator
